### ISSUE TITLE
CORS/Custom Fetcher issue 

### ISSUE THREAD

**Issue by samanhg47** [Dhaiwat10/react-link-preview#11]
I just `npm i`ed the package and it was working for a while but now localhost:3000 is blocked by CORS. I was loving it while it was working 🤕 
request error:
```
Access to fetch at 'https://rlp-proxy.herokuapp.com/v2?url=https://www.npmjs.com/package/@dhaiwat10/react-link-preview'
from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on
the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource
with CORS disabled.
```

**Comment by SamanGriffiths47** [comment]
nevermind, I'm a dummy. lol 😋

**Comment by SamanGriffiths47** [comment]
This is how I'm invoking it:
```
<LinkPreview
          id="Link"
          fallback={<Fallback />}
          url={props.link}
          width="60vw"
          borderRadius="0"
          openInNewTab={true}
          backgroundColor="#dac59f"
/>
```

**Comment by Dhaiwat10** [comment]
This is weird. I just tried it out locally and everything is working fine for me. Can you try on another machine maybe? Or another browser?

**Comment by SamanGriffiths47** [comment]
it's working now. Though I made a `customFetcher` function and the element isn't making calls to the api I deployed. I'm using a `js` file. do you think changing it to a `.jsx` file would help? Or is they component only able to read typescript functions? This is the function:
```
// I've also tried just directly returning response.json() as well as just the naked response

async function customFetcher(url) {
    const response = await axios.get(
      `https://link-previews47.herokuapp.com/v2?url=${url}&
      description=${post.descriptionDisplay}`
    )
    const json = response.json()
    return json.metadata
  }


```

**Comment by SamanGriffiths47** [comment]
scratch that, cors is blocking me again, but if I can get this customFetcher to work it'll be inconsequential.

**Comment by Dhaiwat10** [comment]
No idea to be honest. Lol
