### ISSUE TITLE
Module not found: Can't resolve '@dhaiwat10/react-link-preview'

### ISSUE THREAD

**Issue by marzeaned** [Dhaiwat10/react-link-preview#12]
I have tried yarn and npm..... Any suggestions?

**Comment by Dhaiwat10** [comment]
The package is there live on npm: https://www.npmjs.com/package/@dhaiwat10/react-link-preview

Where are you seeing this error? On running `npm install`?

**Comment by marzeaned** [comment]
Disregard. I am an idiot. I was in wrong directory...

**Comment by Dhaiwat10** [comment]
Haha happens to the best of us.
