### ISSUE TITLE
I am curious to know how this works

### ISSUE THREAD

**Issue by Nithur-M** [Dhaiwat10/react-link-preview#14]
Hello developer, I am curious how this tool works.
Can you give a simple idea of what's behind the scene. Thank you.

**Comment by Dhaiwat10** [comment]
Hey @Nithur-M, the best way to learn how this package works is to read the source code. The `LinkPreview.tsx` file is where most of the logic exists.

This package basically renders some metadata about a URL which is passed to it. By default this package uses a Heroku server hosted by me for the data but you can point it to use your own server/data. Please go through the Readme for the instructions.
